In [1]:
import numpy as np

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['C:\\bld\\numpy_1566878026381\\_h_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\bld\\numpy_1566878026381\\_h_env\\Library\\include']
blas_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['C:\\bld\\numpy_1566878026381\\_h_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\bld\\numpy_1566878026381\\_h_env\\Library\\include']
lapack_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['C:\\bld\\numpy_1566878026381\\_h_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\bld\\numpy_1566878026381\\_h_env\\Library\\include']
lapack_opt_info:
    libraries = ['blas', 'cblas', 'lapack'

In [106]:
np.__version__

'1.17.1'

In [5]:
n = 5

In [6]:
Z = np.zeros(n)

In [7]:
dd

array([0., 0., 0., 0., 0.])

In [67]:
inData = list(input().split())
if inData[-1].isdigit():
    inData.append('float')
else:
    dataType = inData[-1]
Z = np.zeros(list(map(int, inData[:-1])), dtype = inData[-1].split('.')[-1])


2 3


In [68]:
print(Z.dtype)

float64


In [45]:
Z.dtype = np.float64

In [69]:
Z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.info(np.where)

 where(*args, **kwargs)

where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y

In [59]:
np.eye(1 ,int(input()), int(input()))

7
6


array([[0., 0., 0., 0., 0., 0., 1.]])

In [71]:
Z = np.arange(10)

In [63]:
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
Z = Z[::-1]

In [108]:
Z = np.array([[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9],
      [0, 0, 9]])

In [110]:
print(list(Z[np.where(Z>3)]))

[4, 5, 6, 7, 8, 9, 9]


In [107]:
!python -V

Python 3.7.4
