In [11]:
import numpy as np

In [19]:
Z = np.arange(16).reshape(4,4)

In [3]:
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
Z = Z - Z.mean()/Z.std()

In [6]:
Z

array([[-1.62697843, -0.62697843,  0.37302157,  1.37302157],
       [ 2.37302157,  3.37302157,  4.37302157,  5.37302157],
       [ 6.37302157,  7.37302157,  8.37302157,  9.37302157],
       [10.37302157, 11.37302157, 12.37302157, 13.37302157]])

In [24]:
%timeit Z = ([(3<Z)&(Z>9)]*Z*-2+Z)

UnboundLocalError: local variable 'Z' referenced before assignment

In [9]:
Z

array([[[ -1.62697843,  -0.62697843,   0.37302157,   1.37302157],
        [  2.37302157,   3.37302157,   4.37302157,   5.37302157],
        [  6.37302157,   7.37302157,   8.37302157,  -9.37302157],
        [-10.37302157, -11.37302157, -12.37302157, -13.37302157]]])

In [23]:
%timeit Z[(3<Z)&(Z>9)]*=-1

6.02 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
a = np.array([1,2,3])
b = np.array([-3,1,1])
a@b

2

In [31]:
c = np.arange(1,2,0.3,dtype=float)

In [32]:
c

array([1. , 1.3, 1.6, 1.9])

In [8]:
print(sum(range(5),-1))
from numpy import *
b = sum(range(5), -1)

10


In [22]:
Z = np.arange(8)

In [23]:
Z

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
Z <- Z

array([False, False, False, False, False, False, False, False])

In [18]:
Z<z>Z

NameError: name 'z' is not defined

In [19]:
 Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [20]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j])

In [27]:
2 << Z >> 2

array([ 0,  1,  2,  4,  8, 16, 32, 64], dtype=int32)

In [25]:
Z**Z

array([     1,      1,      4,     27,    256,   3125,  46656, 823543],
      dtype=int32)

In [29]:
np.array(0) / np.array(0)

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [30]:
np.array(0) // np.array(0)

d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [31]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [33]:
np.array([np.nan]).astype(int)

array([-2147483648])

In [51]:
b = np.eye(4,5)

In [55]:
b[[0, 3],[1,3]]

array([0., 1.])

In [53]:
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [61]:
np.linalg.inv(b)

LinAlgError: Last 2 dimensions of the array must be square