In [1]:
import numpy as np

In [16]:
Z = np.ones((10,10), dtype = int); Z[1:9, 1:9] = 0;

In [17]:
Z

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
np.pad(Z, 1,'constant', constant_values=(2))

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
       [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [19]:
np.nan == np.nan

False

In [20]:
np.inf > np.nan

False

In [21]:
0 * np.nan

nan

In [23]:
np.isnan(np.nan)

True

In [24]:
np.nan in set([np.nan])

True

In [27]:
0.3 == 3*0.1

False

In [26]:
np.nan - np.nan

nan

In [29]:
n = np.nan
m = np.nan
print(id(n), id(m), sep='\n')
print(id(n) == id(m))
print(n == m)

82353104
82353104
True
False


In [31]:
n = 10
np.eye(n,n)*np.array(np.arange(n))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [45]:
x, k = map(int, input().split())
Z = np.eye(k + abs(x), k + abs(x), x, dtype=int)
Z[Z != 0] = np.arange(1, k+1)
print(Z)

-10 5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0 0 0 0 0 0]]


In [115]:
import numpy as np
n, m = map(int, input().split())
Z = np.ones((n,m))
Z[::2,::2] = 0
Z[1::2, 1::2] = 0



3 8


In [116]:
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [70]:
matrix = np.arange(16).reshape(4,-1)
print(matrix)
print(matrix[::2,::2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2]
 [ 8 10]]


In [127]:
matrix.shape

(4, 4)